// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersAPI.Data;

namespace UsersAPI.Migrations
{
    [DbContext(typeof(UsersAPIContext))]
    [Migration("20190825235351_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserManager.Models.ContactDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("UsersName");

                    b.HasKey("Id");

                    b.HasIndex("UsersName");

                    b.ToTable("ContactDetails");
                });

            modelBuilder.Entity("UserManager.Models.Users", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IdNumber");

                    b.Property<string>("PassportNumber");

                    b.Property<string>("Surname");

                    b.HasKey("Name");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UsersAPI.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutUser");

                    b.Property<string>("ImageContent");

                    b.Property<string>("ImageName");

                    b.Property<string>("UsersName");

                    b.HasKey("ImageId");

                    b.HasIndex("UsersName");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("UserManager.Models.ContactDetails", b =>
                {
                    b.HasOne("UserManager.Models.Users")
                        .WithMany("ContactDetails")
                        .HasForeignKey("UsersName");
                });

            modelBuilder.Entity("UsersAPI.Models.Image", b =>
                {
                    b.HasOne("UserManager.Models.Users")
                        .WithMany("Image")
                        .HasForeignKey("UsersName");
                });
#pragma warning restore 612, 618
        }
    }
}
